Setup testing environment and create unit tests for four components
LifeSG/react-design-system pull request #101
Opened 2023-03-01 07:47 UTC by jeraldlyh

**Changes**
- Setup environment for `@testing-library/react`
- Create unit tests for the following components:
  - Accordion
  - Alert
  - Box Container
  - Breadcrumbs

**Additional information**
- [keep] branch

2023-03-01 23:38 UTC, keithtxw requested changes

2023-03-01 23:38 UTC, keithtxw commented on tests/modules/accordion.spec.tsx
> +import { fireEvent, render, screen, waitFor } from "@testing-library/react";
Could you put these files in the same folder format as the `src` directory. I.e. `tests/accordion/accordion.spec.tsx`

Same for the rest

2023-03-01 23:38 UTC, keithtxw commented on tests/modules/accordion.spec.tsx
> +import { DEFAULT_TEXT, DEFAULT_TITLE } from "../common";
While it is repetitive, i think it is better if we have the constants reside in their file. It keeps the context within the file and makes it easier to maintain in future, esp when there will be more files present

2023-03-01 23:38 UTC, keithtxw commented on tests/modules/accordion.spec.tsx
> +const renderComponent = (
There are a couple of helper functions here. I tend to prefer the unit tests spec to be as high up the file as possible (unless mocking involved). May I suggest to move these helpers down (below the tests) and add a section header instead?

2023-03-02 01:45 UTC, qroll requested changes

2023-03-02 01:45 UTC, qroll commented on tests/modules/accordion.spec.tsx
> +const renderComponent = (
these functions can be moved to the end of the tests with a H1 divider indicating `TEST HELPERS`

2023-03-02 01:45 UTC, qroll commented on tests/modules/accordion.spec.tsx
> +            await waitFor(() => fireEvent.click(getExpandAllItemsButton()));
what is the use of the `waitFor`? I was expecting an `act` here for state updates would be sufficient

2023-03-02 01:45 UTC, qroll commented on tests/modules/alert.spec.tsx
> +            expect(getActionLink()).toBeInTheDocument();
would be good to check the link name to verify that the `actionLink.children` is rendered too

2023-03-02 01:45 UTC, qroll commented on tests/modules/accordion.spec.tsx
> +                expect(element.parentElement.parentElement).toHaveStyle({
an alternative if you don't want to hardcode the traversals is to use ``.closest(`[data-testid="expandable-container"]`)``

2023-03-08 02:50 UTC, keithtxw commented on tests/modules/accordion.spec.tsx
> +            screen.queryByRole("heading", { level: 2 })
i think looking for a particular test id might be more deterministic

2023-03-20 02:14 UTC, keithtxw requested changes

2023-03-23 04:59 UTC, keithtxw approved these changes

2023-03-23 05:14 UTC, merged