Calendar month year styles
LifeSG/react-design-system pull request #115
Opened 2023-03-17 07:08 UTC by Wilker0725

**Changes**
Description of changes...

- [delete] branch

**Changelog entry**

- [BREAKING] Description of change in `calendar-month-year-styles`

**Additional information**

- You may refer to this [ticket](https://www.figma.com/file/us90jOpWBahsqK2VAluPvD/BookingSG-Design-System?node-id=3360-23100&t=XAVj8GNpFBjbbOTT-0)
- Any other information you would like to include

2023-03-20 08:28 UTC, qroll requested changes

2023-03-20 08:28 UTC, qroll commented on src/calendar/calendar-day.tsx
>          ) {
is getting too long, can improve readability by extracting this into a helper function `isDisabled`

something like

```
const isDisabled = (day): boolean => {
  const isOutsideBetweenRange = ...
  const isDisabledDate = ...
  const isStartAfterEnd = ...

  return isOutsideBetweenRange || isDisabledDate || isStartAfterEnd 
}
```

2023-03-20 08:34 UTC, Wilker0725 commented on src/calendar/calendar.tsx
> +    const [isDirty, setIsDirty] = useState<boolean>(false);
1. either one is changed. so the user can only select a valid range (disabled before or disabled after)

2023-03-21 01:24 UTC, qroll requested changes

2023-03-21 01:24 UTC, qroll commented on src/calendar/calendar.tsx
> +    const [isNewSelection, setIsNewSelection] = useState<boolean>(false);
can trouble you to flip the boolean values around for clarity

isNewSelection = true to mean user changed the selection in the calendar
isNewSelection = false to mean it's an existing selection before the calendar was open

2023-03-21 01:52 UTC, qroll approved these changes

2023-03-21 01:52 UTC, merged