File Upload Part 4 - Thumbnail rendering
LifeSG/react-design-system pull request #216
Opened 2023-06-27 15:23 UTC by keithtxw

**Changes**
- Rendering of thumbnail
- Excluding replace button mechanism as the expected interaction has certain complications. Proposing to UX that if required, will deal with it at a later stage. 

- [delete] branch

**Additional information**

- You may refer to this [ticket](https://jira.ship.gov.sg/browse/CCUBE-256)
- [Figma](https://www.figma.com/file/us90jOpWBahsqK2VAluPvD/Flagship-Design-System?type=design&node-id=8475-54069&mode=design&t=hP3MU2zKNTpJhbND-0)

Mock filelist for storybook
```
[
  {
    id: "4",
    name: "img-4.jpg",
    type: "image/jpeg",
    size: 5000,
    description: "Some text here",
    thumbnailImageDataUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: "5",
    name: "pdf-doc-5.pdf",
    type: "application/pdf",
    size: 3000,
  },
  {
    id: "6",
    name: "img-6.jpg",
    type: "image/jpeg",
    size: 12000,
  },
  {
    id: "3",
    name: "img-6.jpg",
    type: "image/jpeg",
    size: 12000,
    errorMessage: "Something went wrong",
  },
  {
    id: "2",
    name: "img-2.jpg",
    type: "image/jpeg",
    size: 2000,
    progress: 0.5,
  },
];
```

2023-06-28 09:25 UTC, keithtxw commented on src/file-upload/file-list-item/file-list-item-thumbnail.tsx
> +    onReplaceClick?: (() => void) | undefined;
Likely to drop this feature in the near term. But will still dedicate some time to explore a better method in future. Can leave the code there for now

2023-06-30 08:01 UTC, qroll requested changes

2023-06-30 09:35 UTC, keithtxw commented on src/shared/progress-bar/progress-bar.tsx
ok i'll fix it in another PR on top of part 5

2023-06-30 09:37 UTC, keithtxw commented on src/file-upload/file-list-item/file-list-item.tsx
> -    const handleKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>) => {
Could have been removed accidentally due to merge conflict resolution. Thanks for spotting. Will restore

2023-06-30 10:37 UTC, qroll approved these changes

2023-06-30 10:37 UTC, merged