Pill Component
LifeSG/react-design-system pull request #232
Opened 2023-07-06 08:34 UTC by afiq0209

**Changes**
Pill Component

- [delete] branch

**Additional information**

- You may refer to this [BOOKINGSG-4382](https://jira.ship.gov.sg/browse/BOOKINGSG-4382)

2023-07-07 05:10 UTC, keithtxw requested changes

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/pill.stories.mdx
> +The `Pill` component comes in 2 type, a `solid` and `outline`.
No need for this. To mention this in the variations

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/pill.stories.mdx
> +                Pending Approval
```suggestion
                Outline style pill
```

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/pill.stories.mdx
> +                Rejected
```suggestion
                Solid style pill
```

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/pill.stories.mdx
> +            <Pill type="outline" colorType="green">
Not needed

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/pill.stories.mdx
> +Example of `Pill` usage with icon.
Add a `Heading3` titled "Pill with icon" and this description is no longer needed

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/pill.stories.mdx
> +The `Pill` component comes in 6 colorType, a `black`, `grey`, `green`, `yellow`, `red`, and `blue` color.
```suggestion
The `Pill` comes in 2 display formats, `outline` and `solid` and there are 6 color variations that can be denoted using the `colorType` prop.
```

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/pill.stories.mdx
> +Color `black` will be the default colorType.
Not needed. The props table already indicated

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/pill.stories.mdx
> +This component also inherits the [HTMLDivAttributes](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDivElement)
To add this within the Props table instead. Refer to `Button` stories

2023-07-07 05:10 UTC, keithtxw commented on src/pill/types.ts
> +export type Type = "outline" | "solid";
Rename to `PillType` since this is exposed all the way to root level. We want to eliminate name clash or confusion

2023-07-07 05:10 UTC, keithtxw commented on src/pill/types.ts
> +export type ColorType = "black" | "grey" | "green" | "yellow" | "red" | "blue";
Rename to `PillColorType`

2023-07-07 05:10 UTC, keithtxw commented on src/pill/types.ts
> +    colorType: ColorType;
If there is a default value, then it should not be mandatory, you also stated `mandatory: false` in the docs

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/doc-elements.tsx
> +export const Label = styled.label`
Use an existing `Text` component?

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/props-table.tsx
> +                description: "The color variations of the pill",
```suggestion
                description: (<>The color style of the <code>Pill</code></>),
```

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/props-table.tsx
> +                mandatory: false,
Save as above

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/props-table.tsx
> +                mandatory: false,
if not mandatory, no need to indicate

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/props-table.tsx
> +                description: "Display icon of the pill",
```suggestion
                description: "A component to be displayed as the icon",
```

2023-07-07 05:10 UTC, keithtxw commented on stories/pill/props-table.tsx
> +                description: "The style of the pill",
```suggestion
                description: (<>The display style of the <code>Pill</code></>),
```

2023-07-07 05:30 UTC, qroll requested changes

2023-07-07 05:30 UTC, qroll commented on src/pill/pill.tsx
> +            <Content>
this extra nesting with `Content` seems redundant, can it be merged with `Wrapper`?

2023-07-07 05:30 UTC, qroll commented on src/pill/pill.tsx
> +        <Wrapper
spread the remaining props to `Wrapper` since the component inherits from a div element

2023-07-10 06:17 UTC, keithtxw requested changes
Can also help me add some test cases particularly
- Checking if `children` passed is rendered accordingly
- Check if icon is passed, then it is rendered

2023-07-10 06:17 UTC, keithtxw commented on src/pill/pill.tsx
> +    className,
Since you are not doing anything to `className`, can let it fall under `otherProps`

2023-07-10 10:37 UTC, keithtxw requested changes

2023-07-10 10:37 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +        const element = screen.getByTestId("pill-component");
I think just doing 
```
expect(screen.getByText(label)).toBeInTheDocument();
```
would be sufficient.

2023-07-10 10:37 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +        const label = "pill statuses";
suggestion
```
const label = "Some label";
```

2023-07-10 10:37 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +    it("should render pill component", () => {
should render the Pill label correctly

2023-07-10 10:37 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +        expect(element.innerHTML).toContain(label);
Dont think this is needed

2023-07-10 10:37 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +            <Pill type="solid" data-testid="pill-component">
if we use `getByText` (suggested below) you need not use `data-testid` already

2023-07-10 10:37 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +        expect(element.innerHTML).not.toContain("svg");
We're not certain of the component so i think this assertion is not required.

2023-07-10 10:37 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +        expect(element).toHaveStyle("background: #282828;");
I tend to not to test for color styles since it could be affected by the theme.

2023-07-10 10:37 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +    it("should render pill component with icon", () => {
suggestion
```
it("should render the Pill with an icon if specified", () => {
```

2023-07-10 10:37 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +        expect(element.innerHTML).toContain("svg");
In this instance using a testid on the icon and asserting the testid can be found would be better.

2023-07-10 10:37 UTC, keithtxw commented on src/pill/pill.tsx
>              data-testid={otherProps["data-testid"] || "pill"}
I think this can be omitted also.

2023-07-11 06:57 UTC, keithtxw requested changes

2023-07-11 06:57 UTC, keithtxw commented on src/pill/pill.tsx
> +            {icon && <div data-testid={"icon"}>{icon}</div>}
Think u misunderstood my comment. I meant to add the test id on the icon in the test instead. Not add it to the component

2023-07-11 06:57 UTC, keithtxw commented on src/pill/pill.tsx
>              data-testid={otherProps["data-testid"] || "pill"}
it's not omitted?

2023-07-11 06:57 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +            <Pill type="solid" data-testid="pill-component">
You can remove the `data-testid` prop already

2023-07-11 06:57 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +        expect(screen.getByTestId("icon")).toBeInTheDocument();
Still add the assertion for label

2023-07-11 06:57 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +    it("should render without an icon if not specified", () => {
This test is not needed.

2023-07-11 06:57 UTC, keithtxw commented on tests/pill/pill.spec.tsx
> +            <Pill type="outline" icon={<PlusCircleFillIcon />}>
When i mentioned add test id to icon i meant this
```
<Pill type="outline" icon={<PlusCircleFillIcon data-testid="icon" />}>
```

2023-07-11 08:46 UTC, keithtxw approved these changes

2023-07-11 08:49 UTC, merged