Bold nested search
LifeSG/react-design-system pull request #268
Opened 2023-08-03 06:22 UTC by Wilker0725

**Changes**
Description of changes...
* Bold text if matches the search term
* Selectable on title label itself
* Update stories and types description

- [delete] branch

- [WARNING] Description of change in `NestedSelect`

2023-08-03 15:17 UTC, qroll requested changes

2023-08-03 15:17 UTC, qroll commented on stories/form/form-nested-select/form-nested-select.stories.mdx
to import the required components
`import { Canvas, Meta, Story } from "@storybook/addon-docs";`

2023-08-03 15:17 UTC, qroll commented on stories/form/form-nested-select/props-table.tsx
> +                    "Specifies key path to select particular option label",
```suggestion
                    "The key path of the selected option",
```

2023-08-03 15:17 UTC, qroll commented on stories/form/form-nested-select/props-table.tsx
> +                    "The visual state to represent the dropdown behavior when dropdown is opened",
```suggestion
                    "Determines if items are expanded or collapsed when the dropdown is opened",
```

2023-08-03 15:17 UTC, qroll commented on stories/form/form-nested-select/props-table.tsx
to include `selectableTitle`, `valueToStringFunction`, and `hideNoResultsDisplay` props

2023-08-03 15:17 UTC, qroll commented on src/shared/nested-dropdown-list/nested-dropdown-list.tsx
side question, is there no max height needed on desktop/tablet?

2023-08-04 01:27 UTC, Wilker0725 commented on src/shared/nested-dropdown-list/list-item.tsx
> +        const startIndex = label.toLowerCase().indexOf(searchTerm);
wa! good catch

2023-08-04 06:39 UTC, qroll approved these changes

2023-08-04 06:42 UTC, merged