Bookingsg 4430
LifeSG/react-design-system pull request #280
Opened 2023-08-11 03:42 UTC by Vimal9412

**Changes**
- add variants of overlay + sticky

- [delete] branch

**Changelog entry**
- Description of changes in `Toast`
- add variants of overlay + sticky (at top of the page)
- add new props `${sticky}`
- animation changes for tablet view

**Additional information**

- You may refer to this [BOOKINGSG-4430](https://jira.ship.gov.sg/browse/BOOKINGSG-4430)
- Figma reference: [link](https://www.figma.com/file/us90jOpWBahsqK2VAluPvD/Flagship-Design-System?node-id=3061%3A19059&mode=dev)

**Labels**
[Enhancement]

2023-08-14 02:23 UTC, qroll requested changes

2023-08-16 03:31 UTC, qroll requested changes

2023-08-16 03:31 UTC, qroll commented on src/toast/toast.styles.tsx
> +    margin: 0 !important;
avoid using `!important`

my suggestion is on line 62, change it to
```
& > svg {
```
to target only the status icons

and reapply the svg height/width to the svg selector within DismissButton

then you can also use `CrossIcon` directly in the toast component

2023-08-21 08:48 UTC, Vimal9412 commented on src/toast/toast.styles.tsx
> +        left: 0;
Yes. For mobile view, the toast should be fullwidth.

2023-08-21 13:13 UTC, qroll commented on src/toast/types.ts
> +    /** Specifies if Toast should be fixed to left. Defaults to true */
```suggestion
    /** Specifies if Toast should be fixed to top. Defaults to true */
```

2023-08-22 04:08 UTC, qroll approved these changes

2023-08-22 04:08 UTC, merged