Slider
LifeSG/react-design-system pull request #376
Opened 2023-12-12 13:33 UTC by qroll

**Changes**
New slider input to select from a range of numeric values. The ranged variant is intended to be used in the histogram

- [delete] branch

**Changelog entry**

- New `InputSlider` and `InputRangeSlider`

**Additional information**

- [Figma](https://www.figma.com/file/us90jOpWBahsqK2VAluPvD/Flagship-Design-System?type=design&node-id=21395-21195&mode=design&t=5drpfCc3SvHCpodI-0)

2023-12-19 02:36 UTC, keithtxw requested changes

2023-12-19 02:36 UTC, keithtxw commented on src/input-slider/input-slider.tsx
> +    const [selection, setSelection] = useState<number[]>(initialiseSelection());
We're missing section headers

2023-12-19 02:36 UTC, keithtxw commented on stories/form/form-range-slider/props-table.tsx
> +                description: "the number of controls",
This looks incorrect

2023-12-19 02:36 UTC, keithtxw commented on stories/form/form-range-slider/props-table.tsx
> +                description: "the number of controls",
Incorrect description

2023-12-19 02:36 UTC, keithtxw commented on stories/form/form-range-slider/props-table.tsx
> +                description: "List of custom colors for each track segment",
Perhaps want to add the requirement that the expected length is (number of values + 1)?

2023-12-19 02:36 UTC, keithtxw commented on stories/form/form-slider/props-table.tsx
> +                description: "the number of controls",
`disabled` and `readOnly` have incorrect descriptions

2023-12-19 02:36 UTC, keithtxw commented on stories/form/form-slider/props-table.tsx
> +                description: "The input values",
```suggestion
                description: "The input value",
```

2023-12-19 12:40 UTC, qroll commented
Updated incorrect prop descriptions and also added documentation for `className`/`data-testid`/`id` and `ariaLabels`

2023-12-20 04:49 UTC, qroll commented
force pushed to rebase changes on top of master

2023-12-20 16:47 UTC, keithtxw requested changes

2023-12-20 16:47 UTC, keithtxw commented on stories/form/form-slider/props-table.tsx
> +                description: "List of custom colors for each track segment",
To add the same description as the one in `form-range-slider` props table

2023-12-21 08:19 UTC, keithtxw approved these changes

2023-12-21 08:19 UTC, merged