Add filter item tooltip
LifeSG/react-design-system pull request #401
Opened 2024-01-24 18:35 UTC by qroll

**Changes**

Add tooltip to filter item title

- [delete] branch

**Changelog entry**

- [BREAKING | WARNING | remove if none] Description of change in `Component-name`

**Additional information**

- Using Floating UI to handle repositioning
- Potential breaking change to popover (have put under a v2 folder for now), to discuss
- Instead of a HOC, use composition. Considering a render prop or hook instead if the composed trigger requires additional data
- Encountered build issues as Rollup v2 couldn't handle the mjs file, upgraded Rollup to v3
- Encountered unit test error, updating the `moduleDirectories` resolves it somehow

2024-01-25 07:49 UTC, qroll commented
fixing some alignment issues with the tooltip icon

2024-01-25 15:22 UTC, qroll commented
partially addresses https://github.com/LifeSG/react-design-system/issues/373

2024-02-02 01:43 UTC, keithtxw requested changes

2024-02-02 01:43 UTC, keithtxw commented on src/form/form-label-addon.tsx
> +    const { content, type, icon, id, "data-testid": dataTestid } = addon;
could we just name it `testId` for consistency with other components

2024-02-02 01:43 UTC, keithtxw commented on src/popover-v2/popover-trigger.tsx
> +    const [visible, setVisible] = useState<boolean>(false);
missing the section headers

2024-02-06 02:04 UTC, keithtxw approved these changes

2024-02-06 03:55 UTC, merged