Support popover position and custom content
LifeSG/react-design-system pull request #402
Opened 2024-01-25 15:19 UTC by qroll

**Changes**

Depends on [this PR](https://github.com/LifeSG/react-design-system/pull/401) to be merged first

- Support custom content: the styling of the popover is awkward as it's in a portal and can't be targeted with `styled-components`. Ended up with a render function which is more flexible
- Support positioning - referenced the allowed types from `Tooltip`
- [delete] branch

2024-03-02 03:58 UTC, keithtxw requested changes

2024-03-02 03:58 UTC, keithtxw commented on stories/popover-v2/props-table.tsx
> +                        The visual of the <code>Popover</code> in relation to
```suggestion
                        The visual position of the <code>Popover</code> in relation to
```

2024-03-07 16:13 UTC, keithtxw requested changes
To fix merge conflicts

2024-03-08 09:03 UTC, qroll commented
> To fix merge conflicts

hmm no new changes

2024-03-09 17:06 UTC, keithtxw approved these changes

2024-03-09 17:06 UTC, merged