[CCUBE-1199][BL] Created new component for button-with-icon
LifeSG/react-design-system pull request #439
Opened 2024-04-01 07:54 UTC by benjaminLeongSK

- Created new component folder
- Added styling and props to position icon
- Created stories 
- Created test cases

2024-04-01 10:18 UTC, benjaminLeongSK commented
Awaiting confirmation from UX regarding how the button will look like with multiple lines of label

2024-04-02 03:18 UTC, keithtxw commented
Discussing if we should extend the existing `Button` component or continue to introduce a new one

2024-04-02 03:21 UTC, keithtxw requested changes

2024-04-02 03:21 UTC, keithtxw commented on src/button-with-icon/button-with-icon.style.tsx
> +export const Main = styled.button<MainStyleProps>`
As per previous discussion, to reuse `Main` in `src/button` and add custom styling if necessary instead of copying.

2024-04-02 03:21 UTC, keithtxw commented on src/button-with-icon/types.ts
> +export interface ButtonWithIconProps
to extend from `src/button/types` instead of respecifying. The only additional stuff is the icon props

2024-04-09 03:56 UTC, keithtxw requested changes

2024-04-09 03:59 UTC, keithtxw requested changes

2024-04-09 03:59 UTC, keithtxw commented on src/button-with-icon/types.ts
> +type StyleType = "default" | "secondary" | "light" | "link";
Not being used.

2024-04-09 04:42 UTC, keithtxw requested changes

2024-04-09 04:42 UTC, keithtxw commented on stories/button-with-icon/props-table.tsx
> +                            href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement"
Add a link to the Button's prop table then you need not respecify the similar props

2024-04-09 04:42 UTC, keithtxw commented on src/button-with-icon/button-with-icon.tsx
> +            {icon} <span>{children}</span>
Have this on double lines instead

2024-04-11 08:05 UTC, keithtxw requested changes
Also missing an export on root level

2024-04-11 08:05 UTC, keithtxw commented on src/button-with-icon/types.ts
> +export interface ButtonWithIconProps extends ButtonProps {
If `loading` is not meant to be introduced, then you can't just import from `ButtonProps`

2024-04-11 08:05 UTC, keithtxw commented on stories/button-with-icon/button-with-icon.mdx
> +<Title>Button With Icon</Title>
```suggestion
<Title>ButtonWithIcon</Title>
```

2024-04-11 08:05 UTC, keithtxw commented on stories/button-with-icon/button-with-icon.mdx
> +The primary call to action component.
```suggestion
The primary call to action component with an icon.
```

2024-04-11 08:15 UTC, keithtxw approved these changes

2024-04-11 08:15 UTC, merged