Fix subtitle font weight
LifeSG/react-design-system pull request #451
Opened 2024-04-16 17:33 UTC by keithtxw

**Changes**
- Fix incorrect weight for subtitle
- Also improve stories to better reflect actual usage

- [delete] branch

**Changelog entry**

- Fix incorrect font weight for `Form.Label` subtitle

**Additional information**

- Fixes [issue](https://github.com/LifeSG/react-design-system/issues/450)

2024-04-18 02:43 UTC, qroll requested changes

2024-04-18 02:43 UTC, qroll commented on stories/form/form-label/form-label.mdx
> +import {RealWorldUsage} from "./form-label.stories"
can remove this unused line

2024-04-18 07:28 UTC, keithtxw commented on stories/form/form-label/form-label.mdx
> +import {RealWorldUsage} from "./form-label.stories"
Yikes. Why is it even there. Ok thanks!

2024-04-19 05:01 UTC, qroll approved these changes

2024-04-19 05:01 UTC, merged