Update alert component
LifeSG/react-design-system pull request #463
Opened 2024-05-02 09:30 UTC by Mono143

**Changes**

-added a new optional customAlertIcon field for Alert component
-added a new optional maxLines field for Alert component
[delete] branch

**Changelog entry**

-Added new optional custom alert icon for Alert component
-Added new optional maxHeight for Alert component

**Additional information**

You may refer to [RBS-1265](https://jira.ship.gov.sg/browse/RBS-1265)

2024-05-02 16:43 UTC, keithtxw requested changes

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.style.tsx
> +export interface TextContentProps {
We try to follow closely to the name of the styled component. So this should be `TextWrapperContainerStyleProps`

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.style.tsx
> +export const ShowMoreButton = styled(Text.BodySmall)`
it is more semantically correct to use a div/button instead. You can use the `TextStyleHelper` if you want the `BodySmall` font

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.tsx
> +import { ChevronDownIcon, ChevronUpIcon } from "@lifesg/react-icons";
import them individually and organise imports

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.tsx
> +        setDisplayShowMore(!!maxHeight);
could you refactor this? I want to refrain from setting the state multiple times. Could you also extract this processing into a helper function

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.tsx
> +    const [isShowMore, setIsShowMore] = useState(false);
Add section header `CONST, STATE, REFS`

2024-05-02 16:43 UTC, keithtxw commented on src/alert/types.ts
> +    customAlertIcon?: JSX.Element | undefined;
```suggestion
    customIcon?: JSX.Element | undefined;
```
Since we already know this is an `Alert` component

2024-05-02 16:43 UTC, keithtxw commented on src/alert/types.ts
> +    /** Specifies the maximum height of the element to be
Could you break the line? usually it should look like this
```
/**
  * Specifies....
  * displayed...
  */
```

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.style.tsx
> +                height: ${props.$maxHeight}px;
actually i thought the max height would mean the entire component's max height rather than the text content?

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.tsx
> +    const [displayShowMore, setDisplayShowMore] = useState<boolean>(false);
`renderShowMore` would be a more standardised way of naming

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.tsx
> +    const [isShowMore, setIsShowMore] = useState(false);
Rename for clarity

```suggestion
    const [showHiddenContent, setShowHiddenContent] = useState<boolean>(false);
```

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.tsx
> +                {maxHeight !== undefined && displayShowMore && (
can just use `renderShowMore`? since that factors in the maxHeight already.

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.tsx
> +                        {isShowMore ? (
can extract this to a render function for better readability of the main return

2024-05-02 16:43 UTC, keithtxw commented on src/alert/alert.tsx
> +                                <ChevronUpIcon />
the ux might want a rotate effect. Good to clarify. It is quite simple to do.

2024-05-02 16:43 UTC, keithtxw commented on stories/alert/alert.mdx
> +<Heading3>With maximum height</Heading3>
```suggestion
<Heading3>With maximum height setting</Heading3>

You can restrict the height of the `Alert` by setting the `maxHeight` to a desired value in px.
```

2024-05-02 16:43 UTC, keithtxw commented on stories/alert/props-table.tsx
> +        <tr>
Could you refactor this to use the object structure? Can refer to the other props table like `Button`

2024-05-02 16:43 UTC, keithtxw commented on tests/alert/alert.spec.tsx
> +        it("should render if the prop is provided", () => {
```suggestion
        it("should render a custom icon if specified", () => {
```

2024-05-02 16:43 UTC, keithtxw commented on tests/alert/alert.spec.tsx
> +        it("should not render if the prop is not provided", () => {
```suggestion
        it("should not render a custom icon by default", () => {
```

2024-05-13 03:28 UTC, qroll requested changes

2024-05-13 03:28 UTC, qroll commented on tests/alert/alert.spec.tsx
> +        it("should not render a custom icon by default", () => {
this test case doesn't seem useful

2024-05-13 03:28 UTC, qroll commented on src/alert/types.ts
> +    collapsedHeight?: number | undefined;
naming can be consistent with the notification banner if possible

```suggestion
    maxCollapsedHeight?: number | undefined;
```

2024-05-13 03:28 UTC, qroll commented on src/alert/alert.tsx
> +    }, [collapsedHeight]);
also need to check if the content height > max collapsed height

the content height should be a hook dependency as well

2024-05-13 03:28 UTC, qroll commented on src/alert/alert.tsx
> +                    {children}
should set the contentResizeDetector on a static div, similar to the notification banner

2024-05-13 03:30 UTC, qroll commented on src/alert/alert.style.tsx
> +export const ShowMoreButton = styled.div`
semantically should be a button

and will need `type="button"` set to avoid unintended form submissions

2024-05-13 06:56 UTC, qroll approved these changes

2024-05-14 01:36 UTC, merged