[MOL-16223][AT] add mylegacy illustrations to DS
LifeSG/react-design-system pull request #526
Opened 2024-07-30 03:03 UTC by thyAshley

**Changes**
Adding Mylegacy error illustrations
Updating stories to allow mylegacy as a illustraion variant

- delete branch

**Changelog entry**
Feature: Added Mylegacy error illustrations
Update: Enhanced stories to include Mylegacy as an illustration variant

**Additional information**
- You may refer to this [MOL-16223](https://jira.ship.gov.sg/browse/MOL-16223)

2024-07-30 13:46 UTC, qroll requested changes

2024-07-30 13:46 UTC, qroll commented on src/theme/types.ts
> +    | "mylegacy";
remember to set this resource for the theme in `src/theme/index.ts` too

2024-07-30 13:46 UTC, qroll commented on src/error-display/error-display-data.tsx
- browser not supported - should that follow MyLegacy's generic error too?
- confirmation and warning are square - the height and width should follow the image dimensions
- confirmation and warning look really huge relative to the other illustrations, should they follow the same aspect ratio?
<img width="1511" alt="Screenshot 2024-07-30 at 9 43 50 PM" src="https://github.com/user-attachments/assets/175d8251-21f8-42c7-b6f1-4b7d34746b58">

2024-07-30 14:04 UTC, thyAshley commented on src/error-display/error-display-data.tsx
1) for those w/o mylegacy specific asset it will default back to lifesg asset
2/3) will check and confirm with UX on this

2024-07-30 14:20 UTC, thyAshley commented on src/error-display/error-display-data.tsx
eh sorry, i check the uploaded image it is 160 for width/height but the 400px width/height is set by the component.
![image](https://github.com/user-attachments/assets/393b9d0c-8ab0-45bd-859a-5f491e204bc5)

2024-07-30 14:24 UTC, thyAshley commented on src/error-display/error-display-data.tsx
question is, can i change the how the image is setup to the following, or is there a reason we hardcode the img width instead of using whats found in the display-data
![image](https://github.com/user-attachments/assets/f7ce4608-2422-4710-92a4-860d883b6b86)

2024-07-31 01:19 UTC, qroll commented on src/error-display/error-display-data.tsx
ok images should follow the general 400px by 2xxpx dimensions

to keep the confirmation/warning proportionate, they should come with built-in spacing
![Screenshot 2024-07-31 at 9 16 44 AM](https://github.com/user-attachments/assets/bdc2f38f-7c66-4735-a416-f50dcd850307)

2024-08-02 02:28 UTC, qroll approved these changes

2024-08-02 02:28 UTC, merged