[BOOKINGSG-5979][WX]add new component SelectHistogram
LifeSG/react-design-system pull request #532
Opened 2024-08-08 07:56 UTC by wx-uf

1. add new component SelectHistogram in DS
2. add storybook and test cases accordingly

2024-08-12 02:54 UTC, choo95dev approved these changes

2024-08-12 03:47 UTC, qroll requested changes

2024-08-12 03:47 UTC, qroll commented on src/select-histogram/types.ts
> +export interface SelectHistogramSliderProps {
to also include the following optional props:
- `className`
- `readOnly`
- `onBlur` - can be typed without the event arg as `() => void`

2024-08-12 03:47 UTC, qroll commented on src/select-histogram/types.ts
> +    histogramSlider: HistogramSliderProps;
can pick specific props instead as not all are used or relevant

i.e.
`Pick<HistogramSliderProps, "bins" | "interval" | "renderEmptyView"> `

and move `onChange`, `rangeLabelPrefix` and `rangeLabelSuffix` to `SelectHistogramSliderProps`

2024-08-12 03:47 UTC, qroll commented on src/select-histogram/select-histogram.tsx
to also include the `focused` handling with `onBlur` callback

2024-08-12 03:47 UTC, qroll commented on src/select-histogram/select-histogram.tsx
> +                id="select-histogram-selector"
don't hardcode, use the props instead

2024-08-14 01:18 UTC, qroll approved these changes

2024-08-16 06:58 UTC, merged