[MOL-16390][Tung] Update touch area of accordion
LifeSG/react-design-system pull request #536
Opened 2024-08-15 10:06 UTC by QuocTung95

**Changes**
Description of changes...

- [keep | delete] branch

**Changelog entry**

- [BREAKING | WARNING | remove if none] Description of change in `Component-name`

**Additional information**

- You may refer to this [ticket](url)
- Any other information you would like to include

2024-08-15 13:21 UTC, qroll requested changes

2024-08-15 13:21 UTC, qroll commented on src/accordion/accordion-item.tsx
this needs to account for the `collapsible` prop

if `collapsible` is false, then the title shouldn't be interactive, and the cursor should remain as the default

2024-08-15 13:21 UTC, qroll commented on src/accordion/accordion-item.tsx
can I confirm if this behaviour should apply to all accordions? or only in specific scenarios?

if the latter, then it should be configurable through a prop

2024-08-16 02:47 UTC, QuocTung95 commented on src/accordion/accordion-item.tsx
it should be apply for all, confirmed form UX

2024-08-16 02:51 UTC, QuocTung95 commented on src/accordion/accordion-item.tsx
But this morning QE said "now the scope has changed. I would like to clarify this with UX on exact accordions that requires this change" in the chat. So wait for me uppdate

2024-08-16 03:45 UTC, QuocTung95 commented on src/accordion/accordion-item.tsx
With new this Accordion we make it as default ( touch area whole title - confirmed ). And with BoxContainer we keep it as old version

2024-08-16 09:39 UTC, QuocTung95 commented on src/accordion/accordion-item.tsx
checked collapsible

2024-08-16 10:18 UTC, qroll approved these changes

2024-08-16 10:18 UTC, merged