[BOOKINGSG-6107][JH] add optional showCurrentMonthOnly prop for Calendar
LifeSG/react-design-system pull request #545
Opened 2024-08-22 08:31 UTC by jhyeep

**Changes**
Add optional `showCurrentMonthOnly` prop for `Calendar`, setting to true will hide all dates outside the current selected month

- delete branch

**Changelog entry**

- Add optional `showCurrentMonthOnly` prop for `Calendar` component

**Additional information**

- You may refer to this [BOOKINGSG-6107](https://jira.ship.gov.sg/browse/BOOKINGSG-6107)

2024-08-22 10:05 UTC, weili-govtech requested changes

2024-08-22 12:53 UTC, jhyeep commented on src/shared/internal-calendar/types.ts
> +    showCurrentMonthOnly?: boolean | undefined;
overflow doesn't fit well enough i think, in the context of days before and after a certain month. how about `hideNonCurrentMonthDays`? or `showCurrentMonthDaysOnly`/`showDaysOfCurrentMonthOnly`?

2024-08-23 07:16 UTC, weili-govtech commented on src/shared/internal-calendar/types.ts
> +    showCurrentMonthOnly?: boolean | undefined;
yeah ok but instead of `current`, use `active`

2024-08-25 06:58 UTC, weili-govtech approved these changes

2024-08-25 06:59 UTC, merged