[BOOKINGSG-6086][JH] Adjust CountdownTimer logic from Math.ceil to floor
LifeSG/react-design-system pull request #549
Opened 2024-08-28 05:45 UTC by jhyeep

**Changes**
- Changed `CountdownTimer` to use `Math.floor()` instead of `ceil` to more accurately reflect the countdown's duration. Currently countdowns are running for 1s longer than they should e.g. a 10s countdown only updates 1s later (hence total runtime = 11s), so it should begin at 9s instead
- Also fixed a typo in the storybook props table for `Filter`. `toggleFilterButtonStyle` was incorrectly named as `toggleFilterButtonType`

- [delete] branch

**Changelog entry**

- [WARNING] Adjust `CountdownTimer` logic for better accuracy (countdowns will now be reduced by 1 second)

**Additional information**

- You may refer to this [BOOKINGSG-6086](https://jira.ship.gov.sg/browse/BOOKINGSG-6086)

2024-08-28 13:30 UTC, weili-govtech requested changes

2024-08-28 13:30 UTC, weili-govtech commented on src/countdown-timer/use-timer.tsx
I dont quite get this change actually, if it's meant to count down for 10s, it should start from 10s? where does the extra 1s come from?

I did a simple console.log with setTimeout and can see the countdown running properly without this fix, what am I missing?

```
useEffect(() => {
    if (!isPlaying) return;
    if (endTime)
        setRemainingSeconds(
            calculateRemainingSecondsFromTimestamp(endTime)
        );

    const startTime = Date.now();
    const intervalId = setInterval(() => {
        const countdown = calculateRemainingSecondsFromTimestamp(
            endTime ?? startTime + seconds * 1000
        );

        setRemainingSeconds(countdown);
        if (countdown <= 0) {
            console.log("countdown ended");
            clearInterval(intervalId);
        }
    }, 1000);

    setTimeout(() => {
        console.log("15s");
    }, 15000);

    return () => clearInterval(intervalId);
}, [endTime, isPlaying, seconds]);
```

2024-08-29 09:35 UTC, jhyeep commented on src/countdown-timer/use-timer.tsx
you're right - i somehow mixed up ceilings, floors and timers that display milliseconds, sorry for the confusion. 

the behavior of the CountdownTimer is currently fine on the surface, but for `timestamp` due to the current 1000 interval logic the timer will likely have inaccuracies up to 1s. i'll be changing the PR to focus on fixing that instead

2024-08-29 14:08 UTC, weili-govtech commented on src/countdown-timer/use-timer.tsx
ok no issues with the new logic. 

just want to point out that, I think by now you probably should be aware that the countdown will never be 100% accurate because it is based on the end user's computer performance. a slower computer will take a longer time to complete the setTimeout.

2024-08-29 14:08 UTC, weili-govtech approved these changes

2024-08-29 14:08 UTC, merged