V3 colour docs
LifeSG/react-design-system pull request #555
Opened 2024-09-05 01:07 UTC by qroll

**Changes**

Stories for the old tokens have been moved into `v2_*` folders

Documentation for the new design tokens, theming info and colour tokens

You may view the docs at
http://localhost:6006/?path=/docs/foundations-introduction--docs
http://localhost:6006/?path=/docs/foundations-themes-introduction--docs
http://localhost:6006/?path=/docs/foundations-colours-introduction--docs

- [delete] branch

2024-09-05 13:15 UTC, weili-govtech requested changes

2024-09-05 13:15 UTC, weili-govtech commented on stories/theme/colour/b-colour-lifesg.mdx
> +<SemanticColourDisplay theme={LifeSGTheme} />
as consumers will be dealing with semantic colours most of the time, it will be better to put them above the primitive colours

2024-09-06 05:08 UTC, qroll commented on .storybook/preview.ts
> +                // OneService: V2_OneServiceTheme,
will be added eventually, still pending the new colour tokens for OS

2024-09-06 05:12 UTC, qroll commented on stories/storybook-common/doc-alert.tsx
> +    }
it was meant to inherit Storybook's default text size, should have used `em` instead

but anyway have removed the `a` styling as it currently looks fine without it

for margin, it meant to follow Storybook's styling for blockquotes which uses `px`

2024-09-09 01:29 UTC, merged