Layout component-section container content
LifeSG/react-design-system pull request #571
Opened 2024-09-23 02:51 UTC by mahidhar-reddy09

Set up layout component for section,container and content.

2024-09-25 01:16 UTC, qroll requested changes

2024-09-25 01:16 UTC, qroll commented on src/layout/container.tsx
> +const StyledContainer = styled.div<StyleProps>`
could you help to move the styled component to a separate file?

2024-09-25 01:16 UTC, qroll commented on src/layout/types.ts
> +    stretch?: boolean;
```suggestion
    stretch?: boolean | undefined;
```

2024-09-25 01:16 UTC, qroll commented on tests/layout/layout-container.spec.tsx
unit tests are not required for these components as they have minimal behaviour and the logic is mostly for visual styling

2024-09-26 04:27 UTC, mahidhar-reddy09 commented on src/layout/container.tsx
> +            case "grid":
Hi Roo Ling I am not sure what does comment means. In the sense that what or how is the theme and breakpoint used other than the current mediaquery breakpoint in the context of this grid case?

2024-09-30 07:07 UTC, qroll requested changes

2024-09-30 07:07 UTC, qroll commented on src/layout/section.tsx
> +    }}
since the margin will be in the container, this doesn't seem to be in use any more

2024-10-01 17:13 UTC, qroll requested changes

2024-10-01 17:13 UTC, qroll commented on src/layout/container.styles.tsx
> +    }
this would take override the styles above. only apply this if `$stretch` is false.

2024-10-02 00:37 UTC, qroll commented on src/layout/container.styles.tsx
> +                padding: 0 32px;
should be based on xxl-margin token

2024-10-03 13:58 UTC, qroll approved these changes

2024-10-03 13:59 UTC, merged