Box shadow theme
LifeSG/react-design-system pull request #87
Opened 2023-02-08 05:41 UTC by qroll

**Changes**

- delete branch

**Changelog entry**

- Add box shadow color theming for input elements

**Additional information**

- You may refer to this [ticket](https://jira.ship.gov.sg/browse/MOL-11471)
- Only tackling inputs in this PR. UX will align on those grey box shadows used in other components

2023-02-08 07:41 UTC, qroll commented on src/smart-app-banner/smart-app-banner.styles.ts
> +    box-shadow: 0 0.125rem 0.5rem rgba(104, 104, 104, 0.25);
some cleanup to match the `Card` component. wanted to extend with `styled(Card)` but encountered a type error, so left it alone for now

2023-02-08 07:43 UTC, qroll commented on src/card/card.style.tsx
> +    box-shadow: 0 0.125rem 0.5rem rgba(104, 104, 104, 0.25);
Convert px to rem. Matched box-shadow with `SmartAppBanner` since that came later.

2023-02-13 01:51 UTC, keithtxw approved these changes

2023-02-13 01:56 UTC, keithtxw requested changes

2023-02-13 01:56 UTC, keithtxw commented on stories/getting-started/themes-props-table.tsx
> +                    <>You may refer to the DesignTokenSet specifications.</>
Are you intending to link this to somewhere?

2023-02-13 02:00 UTC, keithtxw requested changes

2023-02-13 02:00 UTC, keithtxw commented on stories/getting-started/themes-props-table.tsx
> +                propTypes: ["base"],
missing the backtick

2023-02-13 02:00 UTC, keithtxw commented on stories/getting-started/themes-props-table.tsx
> +                name: "options.color",
Since it is sitting under the `ThemeSpecOptions` I don't think you require the `option` prefix

2023-02-13 02:00 UTC, keithtxw commented on stories/getting-started/themes-props-table.tsx
> +                description: <>You may refer to the ColorSet specifications.</>,
Are you intending to link it somewhere?

2023-02-13 02:00 UTC, keithtxw commented on stories/getting-started/themes-props-table.tsx
> +                name: "key.fontFamily",
Same i dont think need the `key` prefix.

2023-02-13 09:58 UTC, merged